REPO_TAGLINE: Foundations of computer science • logic • programming
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: notes
SITE_URL: https://academic-codex.github.io/SCE0601-Introducao-Ciencia-Da-Computacao-I

BG_1: "#064E3B"
BG_2: "#065F46"
TEXT_MAIN: "#ECFDF5"
TEXT_MUTED: "#A7F3D0"
ACCENT: "#34D399"
CARD_RADIUS: "18"